### ISSUE TITLE
Documentation for $.each is wrong

### ISSUE THREAD

**Issue by mmarcon** [tirejs/tire#10]
I almost got my jHERE plugin (https://github.com/mmarcon/jhere) to work with Tire, but I got stuck on `$.each` due to a misleading documentation.

I tried changing the code so it does what the doc says (and it becomes jQuery compatible) but other parts of the code seem to rely on it so all the tests broke. Now it's time to go to bed, but tomorrow I'll try to work on that and submit a pull request.

Docs says it's

``` javascript
$.each([1, 2, 3], function (index, item) {
  // Item is 1, 2, 3 and so on. Index is the position in the array
});

$.each({ hello: 'world' }, function (key, value) {
  // Key is `hello` and value is `world`
});
```

Instead it is

``` javascript
$.each([1, 2, 3], function (item, index, array) {
  // Item is 1, 2, 3 and so on. Index is the position in the array
});

$.each({ hello: 'world' }, function (key, value, object) {
  // Key is `hello` and value is `world`
});
```

**Comment by frozzare** [comment]
The docs for the array is wrong, but we should probably fix so the documentations version is the right version for Tire.

This should be the right version. So the each for array in Tire should be fixed so it matches the documentation.

``` javascript
$.each([1, 2, 3], function (index, item) {}
```

The fix for array each should be send as a pull request to `1.1.1-wip` (will update the readme about `*-wip` branches) if you will try to fix it, you have to change some part of the source code, mostly fix so the callback function takes two arguments, the first should point to the index (probably `index` is a good name for that variable if it don't conflict with something other) and not the value for arrays.

Each for object works as it should and the documentation for that is right. This is what the documentations says.

``` javascript
$.each({ hello: 'world' }, function (key, value) {
  // Key is `hello` and value is `world`
});
```

This is what I get when i test each for object. No third argument that matched the object.

``` javascript
$.each({ hello: "world" }, function () { console.log(arguments); });
["hello", "world"]
```

**Comment by mmarcon** [comment]
Pull request submitted.
